### ISSUE TITLE
create-remix: Valid template raise and error

### ISSUE THREAD

**Issue by pyk** [remix-run/examples#18]
Cannot create new project with the template:

```
✦ npx create-remix@latest --template examples/chakra-ui
🚨 The template could not be verified. Please double check that the template is a valid project directory in https://github.com/remix-run/remix/tree/main/examples and try again.
```

While `chakra-ui` is exists in this directory https://github.com/remix-run/examples/tree/main/chakra-ui

**Comment by MichaelDeBoey** [comment]
This will be fixed once https://github.com/remix-run/remix/pull/4208 is released
