### ISSUE TITLE
Blog tutorial needs update of routing

### ISSUE THREAD

**Issue by pstric** [remix-run/examples#193]
The official Blog Tutorial creates routes in a posts folder. 

This needs to be changed: 
app/routes/posts/index.tsx -> app/routes/posts._index.tsx
app/routes/posts/\$slug.tsx -> app/routes/posts.\$slug.tsx

Later in the tutorial, maybe there is a need for another change.

Instead of making a route to app/routes/posts/admin/\$slug.tsx and changing this to app/routes/posts.admin.\$slug.tsx, you could change app/routes/posts.\$slug.tsx to app/routes/posts.(admin).\$slug.tsx.
This worked for me, but needs extra consideration if one wants a back button on the post view.

I found these solutions on the page Route File Naming (v2)

**Comment by pstric** [comment]
Hmm, I am completely new to React and Remix, so it is absolutely possible, that I did something wrong. But I have tried following the tutorial, both with a local Node installation and by clicking the link to create a new GitPod.

In both cases, remix.config.js contains the line v2_routeConvention: true, which suggest to me as an absolute noob, that the tutorial follows the instructions described in Route File Naming (v2).

Did you at least try to walk through the tutorial before you closed my issue as completed?

**Comment by MichaelDeBoey** [comment]
@pstric The tutorial is indeed using latest `indie-stack`, which has `v2_routeConvention` flag enabled.

I created https://github.com/remix-run/remix/pull/5959 & https://github.com/remix-run/examples/pull/198 to fix unexpected behavior
