### ISSUE TITLE
Blog Tutorial uses Route File Naming (v2)

### ISSUE THREAD

**Issue by pstric** [remix-run/examples#196]
The official Blog Tutorial instructs the reader to create a new Remix project using the command ```npx create-remix@latest --template remix-run/indie-stack blog-tutorial```.

After this command is run, a project is created where ```remix.config.js``` contains this line: ```v2_routeConvention: true```.

This results in a project that deviates slightly from the tutorial.

The index page in this project is not ```app/routes/index.tsx``` as referenced in the tutorial, but ```app/routes/_index.tsx```.

The project uses flat routes as described on the page [Route File Naming (v2)](https://remix.run/docs/en/1.14.3/file-conventions/route-files-v2#route-file-naming-v2).

Also, the reader of this tutorial needs to be aware of other changes to the routing, because of this. In the tutorial, the reader creates routes to the posts and admin pages that the reader needs to change:
```app/routes/posts/index.tsx``` -> ```app/routes/posts._index.tsx```
```app/routes/posts/$slug.tsx``` -> ```app/routes/posts.$slug.tsx```
```app/routes/posts/admin.tsx``` -> ```app/routes/posts.admin.tsx```
```app/routes/posts/admin/index.tsx``` -> ```app/routes/posts.admin._index.tsx```
```app/routes/posts/admin/new.tsx``` -> ```app/routes/posts.admin.new.tsx```

With these small changes, the app, as far as I have been able to determine, works as described in the tutorial.

**Comment by MichaelDeBoey** [comment]
@pstric The tutorial is indeed using latest `indie-stack`, which has `v2_routeConvention` flag enabled.

I created https://github.com/remix-run/remix/pull/5959 & https://github.com/remix-run/examples/pull/198 to fix unexpected behavior
