### ISSUE TITLE
Followed Remix / Stitches Example and getting FOUC

### ISSUE THREAD

**Issue by coreybruyere** [remix-run/examples#2]
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

Visit [https://california-custom-tile.netlify.app/](https://california-custom-tile.netlify.app/) and notice shift of logo due to FOUC. I applied example project found [here](https://california-custom-tile.netlify.app/) and am unable to resolve the flash of unstyled content. I originally followed [this tutorial](https://rossmoody.com/writing/remix-stitches) as it was the only writing I could find at the time tying Stitches and Remix together.

[Here's all the relevant changes](https://github.com/coreybruyere/california-custom-tile/tree/master/app/styles) I made following the example.

### Expected Behavior

Logo should NOT shift from left side to center from a flash of unstyled content (FOUC). Logo should be centered on load

### Actual Behavior

Logo shifts from left side to right because of FOUC.

**Comment by coreybruyere** [comment]
FYI Stitches has largely been abandoned by original contributors and development has dramatically slowed down. I've moved back to SCSS for projects but have my eyes on vanilla-extract.

**Comment by machour** [comment]
@coreybruyere did you see that we just added an example for vanilla extract? 👀

**Comment by machour** [comment]
Closing this stale issue.

**Comment by richardanewman** [comment]
I only experience FOUC with devtools open in firefox. If it's closed, FOUC goes away. In chorme, the font is a little jumpy with dev tools open but no flash. Nothing with devtools closed.

**Comment by Ehesp** [comment]
I came across this also using Streaming + Remix + Tailwind. No idea if related, but I also noticed that 
it does a FOUC when devtools are open (Chrome).

**Comment by merlindru** [comment]
@richardanewman Good catch, when I close the dev tools there's no more FOUC
