### ISSUE TITLE
_official-realtime-app example is buggy

### ISSUE THREAD

**Issue by rgov** [remix-run/examples#253]
When I load the _official-realtime-app example on CodeSandbox, I notice that:

* When viewing a single issue, even though it says, "That title is content editable and will save on blur," when I edit the title it just reverts back after a moment. (**Edit:** Also reproduces on my local machine.)

* The back button in the integrated browser doesn't work. (**Edit:** Doesn't reproduce on my local machine, but pressing the back button takes almost a full second to go back to which is not great for a simple example project in a framework that purports to be very fast.)

**Comment by rgov** [comment]
Also _official-tutorial results in a "502 Bad Gateway" on CodeSandbox. I'm not sure if any of the examples work, I'm 0 for 3...

**Comment by hollandThomas** [comment]
If you `npm run build` and then `npm start`, it works 🤷‍♂️

**Comment by ryanwoodcox** [comment]
`npm run build` and `npm start` does seem to allow the example to function properly.
Why is this example not working correctly when running `npm run dev`?

I see the same issue on the example based on this example that was shown at RemixConf 2023: 
https://github.com/alexanderson1993/remix-live-loader/issues/2

**Comment by machour** [comment]
Hey, sorry folks about the breakage that was introduced at some point by a global commit on the repository.
We have switched the example to Remix V2 & Vite and fixed everything, enjoy !
