### ISSUE TITLE
Infinite scrolling example seems to be broken in codesandbox

### ISSUE THREAD

**Issue by pratikdevdas** [remix-run/examples#269]
The example works fine for a few moments but after 5 minutes when you scroll again the app throws the error in sandbox.

Steps to reproduce: Open the[ link in codesanbox](https://codesandbox.io/s/github/remix-run/examples/tree/main/infinite-scrolling). This is the link present in the mono repo. After it opens, wait for around 5 minutes and scroll down or up for a while.

Error message screenshot : 
![image](https://github.com/remix-run/examples/assets/63319865/1a0ff440-d4fa-4dad-a04e-36df974b056a)

mono-repo link: https://github.com/remix-run/examples/tree/main/infinite-scrolling
@MichaelDeBoey

**Comment by machour** [comment]
I just tried this, and after 10 minutes, getting back to the codesandbox tab, the whole tab was white, then all the UI came back and was on the homepage of the app, not the route I was on.

I don't think this is related to this example, but rather how codesandbox manage its resources.. 

Did this example cause you trouble locally ?
