### ISSUE TITLE
styled-components example not updated

### ISSUE THREAD

**Issue by AxelBriche** [remix-run/examples#28]
I start a new project with `npx create-remix@latest` command and my `entry.server.tsx` file has 111 lines of code.
Styled-components `entry.server.tsx` file has only 29 line of code.

Can you update that example?

The exemple code use `return new Response("<!DOCTYPE html>" + markup, {`
But last remix version use `new PassThrough()` has new body value:

```
          const body = new PassThrough();

          responseHeaders.set("Content-Type", "text/html");

          resolve(
            new Response(body, {
              headers: responseHeaders,
              status: didError ? 500 : responseStatusCode,
            })
          );
```

**Comment by machour** [comment]
A pull request updating the example would be more than welcome. 
Would be more than glad to help if you have some spare time to take care of it!

**Comment by kiliman** [comment]
I believe the new *entry.server* file supports React 18 streamining, whereas most of the older examples use React 17 and `renderToString`.

I'm not sure how simple, if even possible, it is to update the `styled-components` example to the streaming API.

As you can see, styled components first renders the markup as a string, while collecting styles, then injects those styles into the markup. With streaming, the HTML is already being sent to the client while rendering, so nowhere to inject the styles.

https://github.com/remix-run/examples/blob/872b8baa4e4076b03569e49a424f6cc72ae6637d/styled-components/app/entry.server.tsx#L14-L21

**Comment by MichaelDeBoey** [comment]
`styled-components` has an issue about streaming: https://github.com/styled-components/styled-components/issues/3658

**Comment by MichaelDeBoey** [comment]
@AxelBriche I'm working on a PR to update all examples to comply with our templates.

@kiliman `styled-components` has an issue about HTML streaming: https://github.com/styled-components/styled-components/issues/3658

**Comment by MichaelDeBoey** [comment]
@AxelBriche I'm working on a PR to update all examples to be in line with our templates.

@kiliman `styled-components` has an issue about HTML streaming: https://github.com/styled-components/styled-components/issues/3658

**Comment by joglr** [comment]
> @AxelBriche I'm working on a PR to update all examples to be in line with our templates.
> 
> @kiliman `styled-components` has an issue about HTML streaming: [styled-components/styled-components#3658](https://github.com/styled-components/styled-components/issues/3658)

It seems they have documented how to implement a working example with streaming rendering:

https://styled-components.com/docs/advanced#streaming-rendering

This does not work with a streamed response though.

**Comment by iDVB** [comment]
Any motion on this? We're wondering the exact same thing. 
I guess the fallback is to use React 18  with `renderToString` instead?

**Comment by joglr** [comment]
I'm migrating away from styled-components, so I can use i library that supports react 18 streaming rendering 🤷‍♂️

**Comment by MichaelDeBoey** [comment]
@freshollie We would love to get the `styled-components` example updated to work with React 18

**Comment by beeant** [comment]
The example that @freshollie gave works, but why did he receive a thumbs down? Is there something wrong?
