### ISSUE TITLE
MSW example not working

### ISSUE THREAD

**Issue by SylRob** [remix-run/examples#348]
The MSW example seem to not be working anymore.

This error appear in the front and on the server when we try to reach the home page after running
```
npm run dev
```
```
Application Error

FetchError: request to https://my-mock-api.com/ failed, reason: response3.headers.all is not a function
    at NodeClientRequest.<anonymous> (/****/examples/msw/node_modules/@remix-run/web-fetch/src/fetch.js:112:11)
    at NodeClientRequest.emit (node:events:517:28)
    at NodeClientRequest.emit (/****/examples/msw/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:299:22)
    at /****/examples/msw/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:153:14
```

The codeSandbox link seem to also have the same error

BTW: my node version is `v18.18.0`

**Comment by SylRob** [comment]
I forgot to mention that I tried to initialize the service worker like MSW doc is saying : 
```
npx msw init public/ --save
```
It succeeded, but the error still happens.

**Comment by machour** [comment]
Hey @SylRob 

That problem was described in the README, as the used msw version didn't support node's fetch at that time.
I just upgraded the example to latest msw & remix version, and everything should be working fine.

Please open a new issue if you're still facing problems 🙏🏼
