### ISSUE TITLE
Create an example of an app with nested routes

### ISSUE THREAD

**Issue by elliotaplant** [remix-run/examples#376]
I'm trying to organize my routes using [route folders](https://remix.run/docs/en/main/discussion/routes#conventional-route-folders), but I can't seem to get it to work. I came to the examples repo to find a good example, but none of the examples show how to use route folders. Could someone who knows how Remix route folders works create an example? Thanks so much.

**Comment by machour** [comment]
Hi @elliotaplant,

This is a topic extensively covered by the documentation: https://remix.run/docs/en/main/file-conventions/routes#nested-routes

I suggest opening a Q&A conversation in the remix repository if you need guidance, showing us how you setup things and what's not working for you? I'd be happy to help you!
