### ISSUE TITLE
nprogress uses useTransition, should it use useNavigation instead?

### ISSUE THREAD

**Issue by theskillwithin** [remix-run/examples#402]
https://github.com/remix-run/examples/tree/main/nprogress

nprogress uses useTransition, should it use useNavigation instead?

looks like the readme link to useTransition redirect to useNavigation

**Comment by kiliman** [comment]
Yes, this example should be updated to use the `useNavigation` hook. Thanks!

**Comment by theskillwithin** [comment]
oh I see already has PR https://github.com/remix-run/examples/pull/338
