### ISSUE TITLE
Reach UI is not being actively maintained

### ISSUE THREAD

**Issue by DigitalNaut** [remix-run/examples#42]
The sad truth is that the library used in the examples is slowing down development [reach/reach-ui#972](https://github.com/reach/reach-ui/issues/972) which means dependency issues that are already cropping up.

Will the examples be updated if ol' reliable goes down? I'd love to learn how to implement components with Radix or React Aria but I haven't had much luck after a full day of mud wrestling in Remix trying to make the switch. 

For now it's an `.npmrc` file with `legacy-peer-deps=true` as I learned today the hard way. 

Thank you so much! <3

**Comment by machour** [comment]
Hi @DigitalNaut and thank you for putting this under our radar. We will see how things go for reach UI. 

As for your current struggle, please hop on to our discord or create a new discussion in the Discussion tab of the main remix repo. Someone will be able to help. 

Would be amazing if you shared an example once you get everything up and running. 🙏

Closing this issue as it's not really a bug.
