### ISSUE TITLE
Transforming the `socket` example using `vite`

### ISSUE THREAD

**Issue by RiadhAdrani** [remix-run/examples#423]
I want to use `socket.io` with `remix` but the example uses `remix.config.js` as configuration.
I tried to translate the given configuration using the remix plugin, But I was not able.

Thank you.

**Comment by machour** [comment]
We just updated the socket.io example to use Vite in https://github.com/remix-run/examples/pull/490!

    https://github.com/remix-run/examples/tree/main/socket.io

Enjoy & tfadhal w tdallal ya si Riadh 😁
