### ISSUE TITLE
Hydration issue with the Google Analytics example

### ISSUE THREAD

**Issue by realalex** [remix-run/examples#74]
If you put the `<script>` tags in a client-only wrapper, gtag never gets loaded/defined and `gtag.pageview` never fires:
![image](https://user-images.githubusercontent.com/1354110/202560889-d2c19f9e-bfa6-4427-bbc7-44e1c2f583c3.png)

If you follow the `<script>` embedding example from this repo's `root.tsx` file, hydration errors ensue: 
![image](https://user-images.githubusercontent.com/1354110/202561674-362f0477-0d11-4878-a36b-8d132b3827e0.png)

Has anyone had any luck figuring out a way around this?

**Comment by machour** [comment]
+1, I had to rollback to React 17 to get rid of this annoyance
